print("Hello World!")
print("---------------------------------")
name=input("Enter your Name: ")
age=int(input("Enter your Age: "))
prof=input("Enter your profession: ")
add=input("Enter your address: ")
phone=int(input("Enter phone number: "))

print("--------------Details-------------------")
print("Name: ",name)
print("Age: ",age)
print("Profession: ",prof)
print("Address: ",add)
print("Phone: ",phone)
